//------------------------------------------------------------------------------
// <auto-generated>

// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningProject.Projects.¿Ãµø±Ê
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLE2
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string PHONE { get; set; }
        public string AREA { get; set; }
        public Nullable<System.DateTime> DAY { get; set; }
    }
}
